apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-hdfs-name-nfs-pv
  labels:
    release: hadoop-hdfs
spec:
  storageClassName: hadoop-hdfs-name
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/xfs/hdfs/name
    server: 10.18.129.161
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-hdfs-name-nfs-pvc
spec:
  storageClassName: hadoop-hdfs-name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  selector:
    matchLabels:
      release: hadoop-hdfs
