apiVersion: v1
kind: Service
metadata:
  name: hadoop-nn-service
  labels:
    app: hadoop-nn
spec:
  ports:
    - port: 9000
      name: hdfs
    - port: 50070
      name: name-node
  clusterIP: None
  selector:
    app: hadoop-nn
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-nn
spec:
  replicas: 1
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hadoop-nn
  serviceName: hadoop-nn-service
  template:
    metadata:
      labels:
        app: hadoop-nn
    spec:
      containers:
        - name: hadoop-nn
          image: 10.18.127.2:5000/hadoop-py3-2.9.2:v1
          command: ["bash", "-c", "chmod +x /root/bootstrap.sh && /root/bootstrap.sh"]
          resources:
            limits:
              cpu: 12
              memory: "10Gi"
            requests:
              cpu: 10
              memory: "8Gi"
          env:
            - name: HADOOP_CONF_DIR
              value: /etc/hadoop
            - name: NODE_TYPE
              value: NN,RM
          volumeMounts:
            - name: hadoop-config-volume
              mountPath: /etc/hadoop
            - name: hadoop-custom-config-volume
              mountPath: /root/bootstrap
            - name: dfs-name-dir-volume
              mountPath: /root/hadoop/dfs/name
            - name: dfs-data-dir-volume
              mountPath: /root/hadoop/dfs/data
            - name: hadoop-exec-sh
              mountPath: /root/
      volumes:
        - name: hadoop-custom-config-volume
          configMap:
            name: hadoop-custom-config-cm
        - name: hadoop-config-volume
          persistentVolumeClaim:
            claimName: hadoop-config-nfs-pvc
        - name: dfs-name-dir-volume
          persistentVolumeClaim:
            claimName: hadoop-hdfs-name-nfs-pvc
        - name: dfs-data-dir-volume
          emptyDir: {}
        - name: hadoop-exec-sh
          nfs:
            path: /mnt/xfs/hadoop-exec
            server: 10.18.129.161
