apiVersion: v1
kind: Service
metadata:
  name: hadoop-node-manager-service
  labels:
    app: hadoop-node-manager
spec:
  #ports:
    #- port: 50010
      #name: data-node-trans
    #- port: 50075
      #name: data-node-http
  clusterIP: None
  selector:
    app: hadoop-node-manager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-node-manager
spec:
  replicas: 8
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hadoop-node-manager
  serviceName: hadoop-node-manager-service
  template:
    metadata:
      labels:
        app: hadoop-node-manager
    spec:
      containers:
        - name: hadoop-node-manager
          image: 10.18.127.2:5000/hadoop-py3-2.9.2:v2
          command: ["bash", "-c", "chmod +x /root/bootstrap.sh && /root/bootstrap.sh"]
          resources:
            limits:
              cpu: 3
              memory: "5Gi"
            requests:
              cpu: 2
              memory: "3Gi"
          env:
            - name: HADOOP_CONF_DIR
              value: /etc/hadoop
            - name: NODE_TYPE
              value: NM
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: hadoop-config-volume
              mountPath: /etc/hadoop
            - name: hadoop-custom-config-volume
              mountPath: /root/bootstrap
            - name: hadoop-exec-sh
              mountPath: /root/
            - name: env-path
              mountPath: /home/
      volumes:
        - name: hadoop-custom-config-volume
          configMap:
            name: hadoop-custom-config-cm
        - name: hadoop-config-volume
          persistentVolumeClaim:
            claimName: hadoop-config-nfs-pvc
        - name: hadoop-exec-sh
          nfs:
            path: /mnt/xfs/hadoop-exec
            server: 10.18.129.161
        - name: env-path
          nfs:
            path: /mnt/xfs/env-hosts
            server: 10.18.129.161
