apiVersion: v1
kind: Service
metadata:
  name: hadoop-hdfs-ui-service
  labels:
    app: hadoop-nn
spec:
  ports:
    #- port: 8088
      #name: resource-manager
    - port: 50070
      name: name-node
  selector:
    app: hadoop-nn
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-yarn-ui-service
  labels:
    app: hadoop-nn
spec:
  ports:
    - port: 8088
      name: resource-manager
    #- port: 50070
      #name: name-node
  selector:
    app: hadoop-resource-manager
  type: NodePort
